import { createElement } from '@lwc/engine-dom';
import LdsUtils from 'c/ldsUtils';

describe('c-lds-utils', () => {
    afterEach(() => {
       
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
       
        const element = createElement('c-lds-utils', {
            is: LdsUtils
        });

    
        document.body.appendChild(element);

        
        expect(1).toBe(1);
    });
});